### ISSUE TITLE
dds applet channels disappear and shut down on ARTIQ dashboard

### ISSUE THREAD

**Issue by jayichlab** [Jayich-Lab/jax#42]
When moving the dds applet box on the dashboard, one of the channels, (e.g., X-Wing 1092 AOM) disappears and shuts down. The missing channel only reappears when you add another random channel with the Add Widgets button. This has caused ion loss at X-Wing trap.

**Comment by fanmingyu212** [comment]
It is likely a display bug. Temporary workaround: Resizing the applet carefully may make the channel appear, and clicking on the channel when it shows up will fix it there. It is due to that `QListWidget` does not support children that has dynamic contents in it (e.g. button, textbox, etc.). This is a still a bug that we should solve.
